### ISSUE TITLE
Cannot get stack trace in GC - Rebalance Allocation Failed

### ISSUE THREAD

**Issue by OddOsprey** [dzt/shopify-monitor#51]
I am running the monitor on a Digital Ocean -1 GB Memory / 20 GB Disk / NYC3 - Ubuntu 14.04.5 x64
The process seems to be running out of memory but shouldn't the manual garbage collections prevent that from occurring? Does it have to do with the console logs I uncommented so I could watch the monitor function?

Here is the console log: https://pastebin.com/2z87fFLZ
Here is the NPM Debug: https://pastebin.com/4PMV95Y8

Any input appreciated!

**Comment by dzt** [comment]
This issue has been resolved in the latest update

**Comment by OddOsprey** [comment]
Creating a new issue because this is still occurring.

New console log of error: https://pastebin.com/8vNQgvXX

On Digital Ocean -1 GB Memory / 20 GB Disk / NYC3 - Ubuntu 14.04.5 x64

**Comment by Kickbasic** [comment]
did you fix it
