### ISSUE TITLE
semicolons in error log file name

### ISSUE THREAD

**Issue by conradyeung** [dzt/shopify-monitor#91]
`` fs.writeFile(`./logs/${timeStamp}.err`, body, (err) => {``

writing the timestamp as the log file name includes semicolons which causes the log files not to be saved.

**Comment by dzt** [comment]
Good Looks man I'll be sure to resolve the issue.

**Comment by dzt** [comment]
[Resolved](https://github.com/dzt/shopify-monitor/commit/3b69354d00e15d42ee9d037bec72fc43348443ca)

**Comment by conradyeung** [comment]
still not corrected, it's giving me something like this now
`\logs\undefeated.com_Wed Nov 22 2017 03:30:06 GMT+0000 (Coordinated Universal Time).err`
